sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: Meng
name: Meng
description: Less is More --- by Ludwig Mies van der Rohe
baseurl: /MengBlog

theme: jekyll-theme-minimalism
remote_theme: showzeng/Minimalism

show_excerpt: true

# ---- 社交链接 ----
twitter: https://twitter.com/john_mjd64929
weibo: http://weibo.com/JohnMai
github: https://github.com/JohnMai1994/MengBlog
linkedin: https://www.linkedin.com/in/JohnMai1994
email: mailto:mjd64929@icloud.com
rss: true
# ---- 社交链接 ----


# --- 站点统计 ---
# 如果你想开启站点统计，取消下面一行注解，并填写相应统计运营商给的 id，可支持多个同时开启
# site_statistics: true
# cnzz (友盟统计)
# cnzz_id: 1274425891
# Baidu (百度统计)
# baidu_id:
# Google Analytics (谷歌统计)
# google_id:
# --- 站点统计 ---



# --- 打赏设置 ---
# 开启打赏，取消下面一行注解，并将微信和支付宝的收款二维码放置在 /assets/img/ 文件夹下
# 同时图片的文件名必须为 alipay 和 wechat
reward: true
# 打赏的推广语
reward_description: 如果你觉得本文对你有帮助，不妨请我喝瓶肥宅快乐水！谢谢~
# --- 打赏设置 ---

# --- 评论设置 ---
# 开启评论，取消下面一行注解，并填写相应评论运营商提供的 id，目前仅支持来必力和 gitment
# comment: true
# 来必力 uid
# livere_uid:
# gitment 用户主，即 GitHub 用户名
# gitment_owner: showzeng
# GitHub pages 仓库名，如：showzeng.github.io
# gitment_repo: showzeng.github.io
# gitment 提供的对应 id 和 secret
# gitment_client_id: 76bb22ffd69cb9a2dc11
# gitment_secret: 1bc48766be80fbcb2802679ab796d76ac4fafe44
# --- 评论设置 ---

# --- 版权声明 ---
# 禁止复制 (注：启用后仅文章页和关于页禁止复制)
# lock_copy: true
# 禁止右键菜单 (注：为全局设置，启用后所有页面均无法使用右键菜单)
# lock_menu: true
# 复制文本末尾添加版权声明 (注：启用后仅文章页和关于页复制添加版权声明)
copy_with_declaration: true
# --- 版权声明 ---

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-paginate


exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
